sonar.projectKey=unievents
sonar.projectName=UniEvents
sonar.projectVersion=1.0

sonar.sources=backend,frontend

sonar.exclusions=**/.venv/**,**/venv/**,**/node_modules/**,**/__pycache__/**,**/migrations/**,**/dist/**,**/build/**,**/.git/**

sonar.sourceEncoding=UTF-8