"""Add online meeting fields

Revision ID: e1649cc0fbd8
Revises: 21630bcf1eec
Create Date: 2026-05-04 14:14:30.805271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1649cc0fbd8'
down_revision = '21630bcf1eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online_platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('online_meeting_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('online_meeting_url')
        batch_op.drop_column('online_platform')

    # ### end Alembic commands ###
