"""sync material model

Revision ID: 21630bcf1eec
Revises: ce3139ae72fa
Create Date: 2026-04-03 00:28:00.325186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21630bcf1eec'
down_revision = 'ce3139ae72fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('feedback_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploader_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('materials_uploaded_by_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('materials_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploader_id'], ['id'])
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('uploaded_by')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('registrations_event_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('registrations_event_id_fkey'), 'events', ['event_id'], ['id'])

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('materials_event_id_fkey'), 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('materials_uploaded_by_fkey'), 'users', ['uploaded_by'], ['id'])
        batch_op.drop_column('uploader_id')

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feedback_event_id_fkey'), 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
