"""add_ticket_code_to_registration

Revision ID: b37d91c0ff03
Revises: 8c0d9e5e9039
Create Date: 2026-05-08 21:22:02.572499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37d91c0ff03'
down_revision = '8c0d9e5e9039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_code', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_registrations_ticket_code'), ['ticket_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_ticket_code'))
        batch_op.drop_column('ticket_code')

    # ### end Alembic commands ###
